grails-app/domain/myapp/CalendarEvents.groovy
package myapp

class CalendarEvents {
    String title
    Date start
    Date end
    String primaryColor
    String secondaryColor
    boolean allDay
    boolean resizable
    boolean draggable
    User user;

    static constraints = {
        title nullable: false, blank: false
        start nullable: false, blank: false
        end nullable: true, blank: true
        user nullable: false, blank: false
    }
}

grails-app/controllers/myapp/CalendarEventsController.groovy
package myapp

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class CalendarEventsController {

    CalendarEventsService calendarEventsService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    @Secured(['ROLE_ADMIN'])
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond calendarEventsService.list(params), model:[calendarEventsCount: calendarEventsService.count()]
    }

    @Secured(["ROLE_ADMIN", "ROLE_USER"])
    def show(Long id) {
        respond calendarEventsService.get(id)
    }

    @Secured(["ROLE_ADMIN", "ROLE_USER"])
    def create() {
        respond new CalendarEvents(params)
    }

    @Secured(["ROLE_ADMIN", "ROLE_USER"])
    def save(CalendarEvents calendarEvents) {
        if (calendarEvents == null) {
            notFound()
            return
        }

        try {
            calendarEventsService.save(calendarEvents)
        } catch (ValidationException e) {
            respond calendarEvents.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'calendarEvents.label', default: 'CalendarEvents'), calendarEvents.id])
                redirect calendarEvents
            }
            '*' { respond calendarEvents, [status: CREATED] }
        }
    }

    @Secured(["ROLE_ADMIN", "ROLE_USER"])
    def edit(Long id) {
        respond calendarEventsService.get(id)
    }

    @Secured(["ROLE_ADMIN", "ROLE_USER"])
    def update(CalendarEvents calendarEvents) {
        if (calendarEvents == null) {
            notFound()
            return
        }

        try {
            calendarEventsService.save(calendarEvents)
        } catch (ValidationException e) {
            respond calendarEvents.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'calendarEvents.label', default: 'CalendarEvents'), calendarEvents.id])
                redirect calendarEvents
            }
            '*'{ respond calendarEvents, [status: OK] }
        }
    }

    @Secured(["ROLE_ADMIN", "ROLE_USER"])
    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        calendarEventsService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'calendarEvents.label', default: 'CalendarEvents'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    @Secured(["ROLE_ADMIN", "ROLE_USER"])
    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'calendarEvents.label', default: 'CalendarEvents'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/calendarEvents/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'calendarEvents.label', default: 'CalendarEvents')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-calendarEvents" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-calendarEvents" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.calendarEvents}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.calendarEvents}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.calendarEvents}" method="POST">
                <fieldset class="form">
                    <f:all bean="calendarEvents"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/calendarEvents/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'calendarEvents.label', default: 'CalendarEvents')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-calendarEvents" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-calendarEvents" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.calendarEvents}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.calendarEvents}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.calendarEvents}" method="PUT">
                <g:hiddenField name="version" value="${this.calendarEvents?.version}" />
                <fieldset class="form">
                    <f:all bean="calendarEvents"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/calendarEvents/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'calendarEvents.label', default: 'CalendarEvents')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-calendarEvents" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-calendarEvents" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${calendarEventsList}" />

            <div class="pagination">
                <g:paginate total="${calendarEventsCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/calendarEvents/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'calendarEvents.label', default: 'CalendarEvents')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-calendarEvents" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-calendarEvents" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="calendarEvents" />
            <g:form resource="${this.calendarEvents}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.calendarEvents}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>